sudo: required  # Required for docker
services:
  - docker

install:
  - npm install -g dockerlint

script:
  - python ${TRAVIS_BUILD_DIR}/build.py --folder ${TRAVIS_BUILD_DIR}/odoo80 --docker-image vauxoo/odoo-80-image:latest
  - python ${TRAVIS_BUILD_DIR}/build.py --folder ${TRAVIS_BUILD_DIR}/odoo-shippable --docker-image vauxoo/odoo-80-image-shippable-auto:latest
  - python ${TRAVIS_BUILD_DIR}/build.py --folder ${TRAVIS_BUILD_DIR}/odoo100 --docker-image vauxoo/odoo-100-image:latest

after_success:
    # TODO: Add docker push
